// Package redact provides keyed, deterministic pseudonyms for sensitive
// report values. A caller-held key permits controlled correlation across
// runs without making common source and rule names dictionary-testable.
package redact

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"sync"
)

const (
	Algorithm   = "hmac-sha256"
	minKeyBytes = 32
)

// Redactor pseudonymizes values with a caller-held HMAC key.
type Redactor struct {
	key   []byte
	keyID string
}

// New validates and copies an HMAC key. Callers should supply at least 32
// bytes generated by a cryptographically secure random source. The length
// check cannot detect low-entropy key material.
func New(key []byte) (*Redactor, error) {
	if len(key) < minKeyBytes {
		return nil, fmt.Errorf("redaction key must contain at least %d bytes", minKeyBytes)
	}
	owned := append([]byte(nil), key...)
	return &Redactor{key: owned, keyID: digest(owned, "key-id", "deadair-redaction-key-v1")}, nil
}

// Load reads a key from path. A single trailing CR/LF written by common key
// generation commands is ignored; other bytes are key material.
func Load(path string) (*Redactor, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading redaction key file: %w", err)
	}
	data = bytes.TrimSuffix(data, []byte("\r\n"))
	data = bytes.TrimSuffix(data, []byte("\n"))
	return New(data)
}

// KeyID is a non-secret identifier for detecting whether two reports used the
// same correlation key.
func (r *Redactor) KeyID() string { return r.keyID }

// Value returns a domain-separated pseudonym. Prefixes remain visible so
// humans can distinguish rule, source, field, and tenant identifiers.
func (r *Redactor) Value(prefix, value string) string {
	return prefix + "-" + digest(r.key, prefix, value)
}

func digest(key []byte, prefix, value string) string {
	h := hmac.New(sha256.New, key)
	_, _ = h.Write([]byte(prefix))
	_, _ = h.Write([]byte{0})
	_, _ = h.Write([]byte(value))
	return hex.EncodeToString(h.Sum(nil))[:12]
}

var (
	defaultOnce sync.Once
	defaultKey  *Redactor
)

// Default returns a process-local random redactor for callers that do not
// need correlation across process restarts. CLI users can provide a key file
// when stable cross-run identifiers are required.
func Default() *Redactor {
	defaultOnce.Do(func() {
		key := make([]byte, minKeyBytes)
		if _, err := rand.Read(key); err != nil {
			panic(fmt.Sprintf("generating redaction key: %v", err))
		}
		defaultKey, _ = New(key)
	})
	return defaultKey
}
